gapcmon and gpanel_apcmon portability changes. Remove use of GnomeVFSAddress and b_network_changed. Detect whether gnome_vfs_socket_{read,write} requires 4 arguments or 5 and adjust usage accordingly.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -12417,6 +12417,8 @@ fi;
 if test "$GAPCMON_ENABLED" = "yes" -o "$GPANEL_ENABLED" = "yes" ; then
 				GAPCDIR=gapcmon
 
+				if test "$GAPCMON_ENABLED" = "yes" ; then
+
 
 if test "x$ac_cv_env_PKG_CONFIG_set" != "xset"; then
 	if test -n "$ac_tool_prefix"; then
@@ -12531,12 +12533,12 @@ if test -n "$PKG_CONFIG"; then
         pkg_cv_GAPCMON_CFLAGS="$GAPCMON_CFLAGS"
     else
         if test -n "$PKG_CONFIG" && \
-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"gtk+-2.0 glib-2.0 >= 2.4.0 gthread-2.0 gnome-vfs-module-2.0\"") >&5
-  ($PKG_CONFIG --exists --print-errors "gtk+-2.0 glib-2.0 >= 2.4.0 gthread-2.0 gnome-vfs-module-2.0") 2>&5
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"gtk+-2.0 >= 2.4.0 glib-2.0 gthread-2.0 gnome-vfs-module-2.0\"") >&5
+  ($PKG_CONFIG --exists --print-errors "gtk+-2.0 >= 2.4.0 glib-2.0 gthread-2.0 gnome-vfs-module-2.0") 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
-  pkg_cv_GAPCMON_CFLAGS=`$PKG_CONFIG --cflags "gtk+-2.0 glib-2.0 >= 2.4.0 gthread-2.0 gnome-vfs-module-2.0" 2>/dev/null`
+  pkg_cv_GAPCMON_CFLAGS=`$PKG_CONFIG --cflags "gtk+-2.0 >= 2.4.0 glib-2.0 gthread-2.0 gnome-vfs-module-2.0" 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -12549,12 +12551,12 @@ if test -n "$PKG_CONFIG"; then
         pkg_cv_GAPCMON_LIBS="$GAPCMON_LIBS"
     else
         if test -n "$PKG_CONFIG" && \
-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"gtk+-2.0 glib-2.0 >= 2.4.0 gthread-2.0 gnome-vfs-module-2.0\"") >&5
-  ($PKG_CONFIG --exists --print-errors "gtk+-2.0 glib-2.0 >= 2.4.0 gthread-2.0 gnome-vfs-module-2.0") 2>&5
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"gtk+-2.0 >= 2.4.0 glib-2.0 gthread-2.0 gnome-vfs-module-2.0\"") >&5
+  ($PKG_CONFIG --exists --print-errors "gtk+-2.0 >= 2.4.0 glib-2.0 gthread-2.0 gnome-vfs-module-2.0") 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
-  pkg_cv_GAPCMON_LIBS=`$PKG_CONFIG --libs "gtk+-2.0 glib-2.0 >= 2.4.0 gthread-2.0 gnome-vfs-module-2.0" 2>/dev/null`
+  pkg_cv_GAPCMON_LIBS=`$PKG_CONFIG --libs "gtk+-2.0 >= 2.4.0 glib-2.0 gthread-2.0 gnome-vfs-module-2.0" 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -12573,14 +12575,14 @@ else
         _pkg_short_errors_supported=no
 fi
         if test $_pkg_short_errors_supported = yes; then
-	        GAPCMON_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "gtk+-2.0 glib-2.0 >= 2.4.0 gthread-2.0 gnome-vfs-module-2.0"`
+	        GAPCMON_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "gtk+-2.0 >= 2.4.0 glib-2.0 gthread-2.0 gnome-vfs-module-2.0"`
         else
-	        GAPCMON_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "gtk+-2.0 glib-2.0 >= 2.4.0 gthread-2.0 gnome-vfs-module-2.0"`
+	        GAPCMON_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "gtk+-2.0 >= 2.4.0 glib-2.0 gthread-2.0 gnome-vfs-module-2.0"`
         fi
 	# Put the nasty error message in config.log where it belongs
 	echo "$GAPCMON_PKG_ERRORS" >&5
 
-	{ { echo "$as_me:$LINENO: error: Package requirements (gtk+-2.0 glib-2.0 >= 2.4.0 gthread-2.0 gnome-vfs-module-2.0) were not met:
+	{ { echo "$as_me:$LINENO: error: Package requirements (gtk+-2.0 >= 2.4.0 glib-2.0 gthread-2.0 gnome-vfs-module-2.0) were not met:
 
 $GAPCMON_PKG_ERRORS
 
@@ -12591,7 +12593,7 @@ Alternatively, you may set the environment variables GAPCMON_CFLAGS
 and GAPCMON_LIBS to avoid the need to call pkg-config.
 See the pkg-config man page for more details.
 " >&5
-echo "$as_me: error: Package requirements (gtk+-2.0 glib-2.0 >= 2.4.0 gthread-2.0 gnome-vfs-module-2.0) were not met:
+echo "$as_me: error: Package requirements (gtk+-2.0 >= 2.4.0 glib-2.0 gthread-2.0 gnome-vfs-module-2.0) were not met:
 
 $GAPCMON_PKG_ERRORS
 
@@ -12632,9 +12634,7 @@ else
 echo "${ECHO_T}yes" >&6
 	:
 fi
-	GAPCMON_CFLAGS="$GAPCMON_CFLAGS -DVERSION=\\\"$VERSION\\\""
-
-				if test "$GAPCMON_ENABLED" = "yes" ; then
+		GAPCMON_CFLAGS="$GAPCMON_CFLAGS -DVERSION=\\\"$VERSION\\\""
 		GAPCMON=gapcmon
 	fi
 
@@ -12649,12 +12649,12 @@ if test -n "$PKG_CONFIG"; then
         pkg_cv_GPANEL_CFLAGS="$GPANEL_CFLAGS"
     else
         if test -n "$PKG_CONFIG" && \
-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"gtk+-2.0 >= 2.4.0 glib-2.0 gthread-2.0 gconf-2.0 gnome-vfs-module-2.0 libpanelapplet-2.0 libgnomeui-2.0 libbonoboui-2.0\"") >&5
-  ($PKG_CONFIG --exists --print-errors "gtk+-2.0 >= 2.4.0 glib-2.0 gthread-2.0 gconf-2.0 gnome-vfs-module-2.0 libpanelapplet-2.0 libgnomeui-2.0 libbonoboui-2.0") 2>&5
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"gtk+-2.0 >= 2.4.0 glib-2.0 gthread-2.0 gnome-vfs-module-2.0 gconf-2.0 libpanelapplet-2.0 libgnomeui-2.0 libbonoboui-2.0\"") >&5
+  ($PKG_CONFIG --exists --print-errors "gtk+-2.0 >= 2.4.0 glib-2.0 gthread-2.0 gnome-vfs-module-2.0 gconf-2.0 libpanelapplet-2.0 libgnomeui-2.0 libbonoboui-2.0") 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
-  pkg_cv_GPANEL_CFLAGS=`$PKG_CONFIG --cflags "gtk+-2.0 >= 2.4.0 glib-2.0 gthread-2.0 gconf-2.0 gnome-vfs-module-2.0 libpanelapplet-2.0 libgnomeui-2.0 libbonoboui-2.0" 2>/dev/null`
+  pkg_cv_GPANEL_CFLAGS=`$PKG_CONFIG --cflags "gtk+-2.0 >= 2.4.0 glib-2.0 gthread-2.0 gnome-vfs-module-2.0 gconf-2.0 libpanelapplet-2.0 libgnomeui-2.0 libbonoboui-2.0" 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -12667,12 +12667,12 @@ if test -n "$PKG_CONFIG"; then
         pkg_cv_GPANEL_LIBS="$GPANEL_LIBS"
     else
         if test -n "$PKG_CONFIG" && \
-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"gtk+-2.0 >= 2.4.0 glib-2.0 gthread-2.0 gconf-2.0 gnome-vfs-module-2.0 libpanelapplet-2.0 libgnomeui-2.0 libbonoboui-2.0\"") >&5
-  ($PKG_CONFIG --exists --print-errors "gtk+-2.0 >= 2.4.0 glib-2.0 gthread-2.0 gconf-2.0 gnome-vfs-module-2.0 libpanelapplet-2.0 libgnomeui-2.0 libbonoboui-2.0") 2>&5
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"gtk+-2.0 >= 2.4.0 glib-2.0 gthread-2.0 gnome-vfs-module-2.0 gconf-2.0 libpanelapplet-2.0 libgnomeui-2.0 libbonoboui-2.0\"") >&5
+  ($PKG_CONFIG --exists --print-errors "gtk+-2.0 >= 2.4.0 glib-2.0 gthread-2.0 gnome-vfs-module-2.0 gconf-2.0 libpanelapplet-2.0 libgnomeui-2.0 libbonoboui-2.0") 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
-  pkg_cv_GPANEL_LIBS=`$PKG_CONFIG --libs "gtk+-2.0 >= 2.4.0 glib-2.0 gthread-2.0 gconf-2.0 gnome-vfs-module-2.0 libpanelapplet-2.0 libgnomeui-2.0 libbonoboui-2.0" 2>/dev/null`
+  pkg_cv_GPANEL_LIBS=`$PKG_CONFIG --libs "gtk+-2.0 >= 2.4.0 glib-2.0 gthread-2.0 gnome-vfs-module-2.0 gconf-2.0 libpanelapplet-2.0 libgnomeui-2.0 libbonoboui-2.0" 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -12691,14 +12691,14 @@ else
         _pkg_short_errors_supported=no
 fi
         if test $_pkg_short_errors_supported = yes; then
-	        GPANEL_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "gtk+-2.0 >= 2.4.0 glib-2.0 gthread-2.0 gconf-2.0 gnome-vfs-module-2.0 libpanelapplet-2.0 libgnomeui-2.0 libbonoboui-2.0"`
+	        GPANEL_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "gtk+-2.0 >= 2.4.0 glib-2.0 gthread-2.0 gnome-vfs-module-2.0 gconf-2.0 libpanelapplet-2.0 libgnomeui-2.0 libbonoboui-2.0"`
         else
-	        GPANEL_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "gtk+-2.0 >= 2.4.0 glib-2.0 gthread-2.0 gconf-2.0 gnome-vfs-module-2.0 libpanelapplet-2.0 libgnomeui-2.0 libbonoboui-2.0"`
+	        GPANEL_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "gtk+-2.0 >= 2.4.0 glib-2.0 gthread-2.0 gnome-vfs-module-2.0 gconf-2.0 libpanelapplet-2.0 libgnomeui-2.0 libbonoboui-2.0"`
         fi
 	# Put the nasty error message in config.log where it belongs
 	echo "$GPANEL_PKG_ERRORS" >&5
 
-	{ { echo "$as_me:$LINENO: error: Package requirements (gtk+-2.0 >= 2.4.0 glib-2.0 gthread-2.0 gconf-2.0 gnome-vfs-module-2.0 libpanelapplet-2.0 libgnomeui-2.0 libbonoboui-2.0) were not met:
+	{ { echo "$as_me:$LINENO: error: Package requirements (gtk+-2.0 >= 2.4.0 glib-2.0 gthread-2.0 gnome-vfs-module-2.0 gconf-2.0 libpanelapplet-2.0 libgnomeui-2.0 libbonoboui-2.0) were not met:
 
 $GPANEL_PKG_ERRORS
 
@@ -12709,7 +12709,7 @@ Alternatively, you may set the environment variables GPANEL_CFLAGS
 and GPANEL_LIBS to avoid the need to call pkg-config.
 See the pkg-config man page for more details.
 " >&5
-echo "$as_me: error: Package requirements (gtk+-2.0 >= 2.4.0 glib-2.0 gthread-2.0 gconf-2.0 gnome-vfs-module-2.0 libpanelapplet-2.0 libgnomeui-2.0 libbonoboui-2.0) were not met:
+echo "$as_me: error: Package requirements (gtk+-2.0 >= 2.4.0 glib-2.0 gthread-2.0 gnome-vfs-module-2.0 gconf-2.0 libpanelapplet-2.0 libgnomeui-2.0 libbonoboui-2.0) were not met:
 
 $GPANEL_PKG_ERRORS
 
@@ -12753,6 +12753,64 @@ fi
 		GPANEL_CFLAGS="$GPANEL_CFLAGS -DVERSION=\\\"$VERSION\\\""
 		GPANEL=gpanel_apcmon
 	fi
+
+				_cflags=${CFLAGS}
+	_ldflags=${LDFLAGS}
+	CFLAGS="${CFLAGS} ${GAPCMON_CFLAGS}"
+	LDFLAGS="${LDFLAGS} ${GAPCMON_LDFLAGS}"
+	echo "$as_me:$LINENO: checking if gnome_vfs_socket_read requires cancellation argument" >&5
+echo $ECHO_N "checking if gnome_vfs_socket_read requires cancellation argument... $ECHO_C" >&6
+	cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <libgnomevfs/gnome-vfs.h>
+int
+main ()
+{
+gnome_vfs_socket_read(NULL, NULL, 0, NULL, NULL);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+	      GAPCMON_CFLAGS="${GAPCMON_CFLAGS} -DGNOMEVFS_REQUIRES_CANCELLATION"
+	      GPANEL_CFLAGS="${GPANEL_CFLAGS} -DGNOMEVFS_REQUIRES_CANCELLATION"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+	CFLAGS=${_cflags}
+	LDFLAGS=${_lflags}
 fi
 
 LD="$CXX"
