If libusb-config is not found, fall back on a plain old AC_CHECK_LIB. This will allow building against the new libusb-1.x with compatibility API.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -10577,7 +10577,7 @@ echo "${ECHO_T}Using Linux USB driver." >&6
 echo "${ECHO_T}Using BSD USB driver." >&6
             ;;
          *)
-            # Extract the first word of "libusb-config", so it can be a program name with args.
+                        # Extract the first word of "libusb-config", so it can be a program name with args.
 set dummy libusb-config; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
@@ -10616,14 +10616,85 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
-            if test x$usbcfg = x ; then
-               { { echo "$as_me:$LINENO: error: Cannot find libusb-config" >&5
-echo "$as_me: error: Cannot find libusb-config" >&2;}
+            if test x$usbcfg != x ; then
+               LIBUSB=`$usbcfg --libs`
+               LIBUSBH=`$usbcfg --prefix`/include/usb.h
+            else
+               echo "$as_me:$LINENO: checking for usb_init in -lusb" >&5
+echo $ECHO_N "checking for usb_init in -lusb... $ECHO_C" >&6
+if test "${ac_cv_lib_usb_usb_init+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lusb $DRVLIBS $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char usb_init ();
+int
+main ()
+{
+usb_init ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_usb_usb_init=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_usb_usb_init=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_usb_usb_init" >&5
+echo "${ECHO_T}$ac_cv_lib_usb_usb_init" >&6
+if test $ac_cv_lib_usb_usb_init = yes; then
+  LIBUSB=-lusb
+                             LIBUSBH=usb.h
+else
+  { { echo "$as_me:$LINENO: error: Unable to find libusb" >&5
+echo "$as_me: error: Unable to find libusb" >&2;}
    { (exit 1); exit 1; }; }
+fi
+
             fi
 
-            LIBUSB=`$usbcfg --libs`
-            LIBUSBH=`$usbcfg --prefix`/include/usb.h
 
 
             LIBUSBHIDINC="-I\$(topdir)/src/libusbhid"
