Check for gnome_vfs_socket_set_timeout() and stub it out if not available.

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -12658,6 +12658,70 @@ rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
       CFLAGS=${_cflags}
       LIBS=${_libs}
+
+                        _cflags=${CFLAGS}
+      _libs=${LIBS}
+      CFLAGS="${CFLAGS} ${GAPCMON_CFLAGS}"
+      LIBS="${LDFLAGS} ${GAPCMON_LIBS}"
+      echo "$as_me:$LINENO: checking for gnome_vfs_socket_set_timeout" >&5
+echo $ECHO_N "checking for gnome_vfs_socket_set_timeout... $ECHO_C" >&6
+      cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <libgnomevfs/gnome-vfs.h>
+                          #ifdef GNOMEVFS_REQUIRES_CANCELLATION
+                          #define GNOMEVFS_CANCELLATION ,NULL
+                          #else
+                          #define GNOMEVFS_CANCELLATION
+                          #endif
+int
+main ()
+{
+gnome_vfs_socket_set_timeout(NULL, NULL GNOMEVFS_CANCELLATION);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+            GAPCMON_CFLAGS="${GAPCMON_CFLAGS} -DHAVE_GNOMEVFS_SOCKET_SET_TIMEOUT"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+      CFLAGS=${_cflags}
+      LIBS=${_libs}
+
    fi
 fi;
 
