Simplify SNMP rules. Prefer net-snmp, but fall back on ucd-snmp if it is not found. Look for snmp libs in /usr/local. --enable-snmp and --enable-net-snmp act identically now.

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -10248,14 +10248,27 @@ _ACEOF
 fi;
 
 
-SNMP_DRIVER_ENABLED="no"
-NET_SNMP_DRIVER_ENABLED="no"
+WANT_SNMP="no"
 # Check whether --enable-snmp or --disable-snmp was given.
 if test "${enable_snmp+set}" = set; then
   enableval="$enable_snmp"
    if test "$enableval" = "yes" ; then
-	    SNMP_DRIVER_ENABLED="yes"
-	    echo "$as_me:$LINENO: checking for EVP_DigestInit in -lcrypto" >&5
+	    WANT_SNMP="yes"
+	  fi
+
+fi;
+
+# Check whether --enable-net-snmp or --disable-net-snmp was given.
+if test "${enable_net_snmp+set}" = set; then
+  enableval="$enable_net_snmp"
+   if test "$enableval" = "yes" ; then
+	    WANT_SNMP="yes"
+	  fi
+
+fi;
+
+if test "$WANT_SNMP" = "yes" ; then
+		echo "$as_me:$LINENO: checking for EVP_DigestInit in -lcrypto" >&5
 echo $ECHO_N "checking for EVP_DigestInit in -lcrypto... $ECHO_C" >&6
 if test "${ac_cv_lib_crypto_EVP_DigestInit+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -10323,7 +10336,90 @@ if test $ac_cv_lib_crypto_EVP_DigestInit = yes; then
   echo '	including crypto library for snmp.'; LIBS="$LIBS -lcrypto"
 fi
 
-	    echo "$as_me:$LINENO: checking for snmp_open in -lsnmp" >&5
+
+	WANT_NET_SNMP="yes"
+	SNMP_LIB_FOUND="no"
+
+		_cppflags=${CPPFLAGS}
+	_ldflags=${LDFLAGS}
+	CPPFLAGS="${CPPFLAGS} -I/usr/local/include"
+	LDFLAGS="${LDFLAGS} -L/usr/local/lib"
+
+		if test "$SNMP_LIB_FOUND" = "no" ; then
+		echo "$as_me:$LINENO: checking for snmp_open in -lnetsnmp" >&5
+echo $ECHO_N "checking for snmp_open in -lnetsnmp... $ECHO_C" >&6
+if test "${ac_cv_lib_netsnmp_snmp_open+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lnetsnmp  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char snmp_open ();
+int
+main ()
+{
+snmp_open ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_netsnmp_snmp_open=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_netsnmp_snmp_open=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_netsnmp_snmp_open" >&5
+echo "${ECHO_T}$ac_cv_lib_netsnmp_snmp_open" >&6
+if test $ac_cv_lib_netsnmp_snmp_open = yes; then
+  LIBS="$LIBS -lnetsnmp"
+		   SNMP_LIB_FOUND="yes"
+fi
+
+	fi
+
+		if test "$SNMP_LIB_FOUND" = "no" ; then
+		WANT_NET_SNMP="no"
+		echo "$as_me:$LINENO: checking for snmp_open in -lsnmp" >&5
 echo $ECHO_N "checking for snmp_open in -lsnmp... $ECHO_C" >&6
 if test "${ac_cv_lib_snmp_snmp_open+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -10389,270 +10485,38 @@ echo "$as_me:$LINENO: result: $ac_cv_lib_snmp_snmp_open" >&5
 echo "${ECHO_T}$ac_cv_lib_snmp_snmp_open" >&6
 if test $ac_cv_lib_snmp_snmp_open = yes; then
   LIBS="$LIBS -lsnmp"
-else
-  echo "$as_me:$LINENO: checking for snmp_open in -lnetsnmp" >&5
-echo $ECHO_N "checking for snmp_open in -lnetsnmp... $ECHO_C" >&6
-if test "${ac_cv_lib_netsnmp_snmp_open+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lnetsnmp  $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-/* Override any gcc2 internal prototype to avoid an error.  */
-#ifdef __cplusplus
-extern "C"
-#endif
-/* We use char because int might match the return type of a gcc2
-   builtin and then its argument prototype would still apply.  */
-char snmp_open ();
-int
-main ()
-{
-snmp_open ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_cv_lib_netsnmp_snmp_open=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-ac_cv_lib_netsnmp_snmp_open=no
-fi
-rm -f conftest.err conftest.$ac_objext \
-      conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-echo "$as_me:$LINENO: result: $ac_cv_lib_netsnmp_snmp_open" >&5
-echo "${ECHO_T}$ac_cv_lib_netsnmp_snmp_open" >&6
-if test $ac_cv_lib_netsnmp_snmp_open = yes; then
-  LIBS="$LIBS -lnetsnmp"
-		 NET_SNMP_DRIVER_ENABLED="yes"
-else
-  { { echo "$as_me:$LINENO: error: Cannot find SNMP libraries." >&5
-echo "$as_me: error: Cannot find SNMP libraries." >&2;}
-   { (exit 1); exit 1; }; }
-fi
-
-
+		   SNMP_LIB_FOUND="yes"
 fi
 
 	fi
-fi;
 
-if test "$SNMP_DRIVER_ENABLED" = "yes"; then
-  cat >>confdefs.h <<\_ACEOF
+	if test "$SNMP_LIB_FOUND" = "no" ; then
+	  { { echo "$as_me:$LINENO: error: Cannot find SNMP libraries." >&5
+echo "$as_me: error: Cannot find SNMP libraries." >&2;}
+   { (exit 1); exit 1; }; }
+	fi
+
+		cat >>confdefs.h <<\_ACEOF
 #define HAVE_SNMP_DRIVER 1
 _ACEOF
 
-  if test "$NET_SNMP_DRIVER_ENABLED" = "yes"; then
-     cat >>confdefs.h <<\_ACEOF
+	if test "$WANT_NET_SNMP" = "yes" ; then
+	     cat >>confdefs.h <<\_ACEOF
 #define HAVE_NET_SNMP 1
 _ACEOF
 
-     DISPLAY_SNMP_DRIVER="net-snmp"
-  else
-     cat >>confdefs.h <<\_ACEOF
+	     DISPLAY_SNMP_DRIVER="net-snmp"
+	else
+	     cat >>confdefs.h <<\_ACEOF
 #define HAVE_UCD_SNMP 1
 _ACEOF
 
-     DISPLAY_SNMP_DRIVER="snmp"
-  fi
-  SNMP_DRIVER="snmp"
-
-fi
-
-# Check whether --enable-net-snmp or --disable-net-snmp was given.
-if test "${enable_net_snmp+set}" = set; then
-  enableval="$enable_net_snmp"
-   if test "$enableval" = "yes" ; then
-		NET_SNMP_DRIVER_ENABLED="yes"
-		echo "$as_me:$LINENO: checking for EVP_DigestInit in -lcrypto" >&5
-echo $ECHO_N "checking for EVP_DigestInit in -lcrypto... $ECHO_C" >&6
-if test "${ac_cv_lib_crypto_EVP_DigestInit+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lcrypto  $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-/* Override any gcc2 internal prototype to avoid an error.  */
-#ifdef __cplusplus
-extern "C"
-#endif
-/* We use char because int might match the return type of a gcc2
-   builtin and then its argument prototype would still apply.  */
-char EVP_DigestInit ();
-int
-main ()
-{
-EVP_DigestInit ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_cv_lib_crypto_EVP_DigestInit=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-ac_cv_lib_crypto_EVP_DigestInit=no
-fi
-rm -f conftest.err conftest.$ac_objext \
-      conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-echo "$as_me:$LINENO: result: $ac_cv_lib_crypto_EVP_DigestInit" >&5
-echo "${ECHO_T}$ac_cv_lib_crypto_EVP_DigestInit" >&6
-if test $ac_cv_lib_crypto_EVP_DigestInit = yes; then
-  echo '  including crypto library for snmp.'; LIBS="$LIBS -lcrypto"
-fi
-
-	    echo "$as_me:$LINENO: checking for snmp_open in -lnetsnmp" >&5
-echo $ECHO_N "checking for snmp_open in -lnetsnmp... $ECHO_C" >&6
-if test "${ac_cv_lib_netsnmp_snmp_open+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lnetsnmp  $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-/* Override any gcc2 internal prototype to avoid an error.  */
-#ifdef __cplusplus
-extern "C"
-#endif
-/* We use char because int might match the return type of a gcc2
-   builtin and then its argument prototype would still apply.  */
-char snmp_open ();
-int
-main ()
-{
-snmp_open ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_cv_lib_netsnmp_snmp_open=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-ac_cv_lib_netsnmp_snmp_open=no
-fi
-rm -f conftest.err conftest.$ac_objext \
-      conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-echo "$as_me:$LINENO: result: $ac_cv_lib_netsnmp_snmp_open" >&5
-echo "${ECHO_T}$ac_cv_lib_netsnmp_snmp_open" >&6
-if test $ac_cv_lib_netsnmp_snmp_open = yes; then
-  LIBS="$LIBS -lnetsnmp"
-else
-  { { echo "$as_me:$LINENO: error: Cannot find SNMP libraries." >&5
-echo "$as_me: error: Cannot find SNMP libraries." >&2;}
-   { (exit 1); exit 1; }; }
-fi
-
+	     DISPLAY_SNMP_DRIVER="snmp"
 	fi
-fi;
 
-if test "$NET_SNMP_DRIVER_ENABLED" = "yes"; then
-  cat >>confdefs.h <<\_ACEOF
-#define HAVE_SNMP_DRIVER 1
-_ACEOF
-
-  cat >>confdefs.h <<\_ACEOF
-#define HAVE_NET_SNMP 1
-_ACEOF
-
-  DISPLAY_SNMP_DRIVER="net-snmp"
-  SNMP_DRIVER="snmp"
+	SNMP_DRIVER="snmp"
 
 fi
-
 
 # Check whether --enable-test or --disable-test was given.
 if test "${enable_test+set}" = set; then
