Test net driver + misc

diff --git a/platforms/apccontrol.in b/platforms/apccontrol.in
--- a/platforms/apccontrol.in
+++ b/platforms/apccontrol.in
@@ -51,94 +51,95 @@ then
     ${SCRIPTDIR}/${1} ${2} ${3} ${4}
     # exit code 99 means he does not want us to do default action
     if [ $? = 99 ] ; then
-        exit 0
+	exit 0
     fi
 fi
 
 case "$1" in
     killpower)
-        echo "Apccontrol doing: ${APCUPSD} --killpower on UPS ${2}"
-        echo "Apccontrol doing: ${APCUPSD} --killpower on UPS ${2}" | wall
-        ${APCUPSD} --killpower
+	echo "Apccontrol doing: ${APCUPSD} --killpower on UPS ${2}"
+	echo "Apccontrol doing: ${APCUPSD} --killpower on UPS ${2}" | wall
+	sleep 10
+	${APCUPSD} --killpower
     ;;
     commfailure)
-        echo "Warning communications lost with UPS ${2}" | wall
+	echo "Warning communications lost with UPS ${2}" | wall
     ;;
     commok)
-        echo "Communciations restored with UPS ${2}" | wall
+	echo "Communciations restored with UPS ${2}" | wall
     ;;
     powerout)
-        echo "Warning power loss detected on UPS ${2}" | wall
+	echo "Warning power loss detected on UPS ${2}" | wall
     ;;
     onbattery)
-        echo "Power failure on UPS ${2}. Running on batteries." | wall
+	echo "Power failure on UPS ${2}. Running on batteries." | wall
     ;;
     failing)
-        echo "Battery power exhaused on UPS ${2}. Doing shutdown." | wall
+	echo "Battery power exhaused on UPS ${2}. Doing shutdown." | wall
     ;;
     timeout)
-        echo "Battery time limit exceded on UPS ${2}. Doing shutdown." | wall
+	echo "Battery time limit exceded on UPS ${2}. Doing shutdown." | wall
     ;;
     loadlimit)
-        echo "Remaining battery charge below limit on UPS ${2}. Doing shutdown." | wall
+	echo "Remaining battery charge below limit on UPS ${2}. Doing shutdown." | wall
     ;;
     runlimit)
-        echo "Remaining battery runtime below limit on UPS ${2}. Doing shutdown." | wall
+	echo "Remaining battery runtime below limit on UPS ${2}. Doing shutdown." | wall
     ;;
     doreboot)
-        echo "UPS ${2} initiating Reboot Sequence" | wall
-        ${SHUTDOWN} -r now "apcupsd UPS ${2} initiated reboot"
+	echo "UPS ${2} initiating Reboot Sequence" | wall
+	${SHUTDOWN} -r now "apcupsd UPS ${2} initiated reboot"
     ;;
     doshutdown)
-        echo "UPS ${2} initiated Shutdown Sequence" | wall
-        ${SHUTDOWN} -h now "apcupsd UPS ${2} initiated shutdown"
+	echo "UPS ${2} initiated Shutdown Sequence" | wall
+	${SHUTDOWN} -h now "apcupsd UPS ${2} initiated shutdown"
     ;;
     mainsback)
-        echo "Power has returned on UPS ${2}..." | wall
-        if [ -f @PWRFAILDIR@/powerfail ] ; then
-             echo "Attempting to cancel shutdown." | wall
-             ${SHUTDOWN} -c
-             ${SHUTDOWN} -r now "apcupsd initiated reboot"
-        fi
+	echo "Power has returned on UPS ${2}..." | wall
+	if [ -f @PWRFAILDIR@/powerfail ] ; then
+	     echo "Attempting to cancel shutdown." | wall
+	     ${SHUTDOWN} -c
+	     ${SHUTDOWN} -r now "apcupsd initiated reboot"
+	fi
     ;;
     annoyme)
-        echo "Power problems with UPS ${2}. Please logoff." | wall
+	echo "Power problems with UPS ${2}. Please logoff." | wall
     ;;
     emergency)
-        echo "Emergency Shutdown. Possible battery failure on UPS ${2}." | wall
-        ${SHUTDOWN} -h now "apcupsd emergency shutdown"
+	echo "Emergency Shutdown. Possible battery failure on UPS ${2}." | wall
+	${SHUTDOWN} -h now "apcupsd emergency shutdown"
     ;;
     changeme)
-        echo "Emergency! Batteries have failed on UPS ${2}. Change them NOW" | wall
+	echo "Emergency! Batteries have failed on UPS ${2}. Change them NOW" | wall
     ;;
     remotedown)
-        echo "Remote Shutdown. Beginning Shutdown Sequence." | wall
-        ${SHUTDOWN} -h now "apcupsd remote shutdown"
+	echo "Remote Shutdown. Beginning Shutdown Sequence." | wall
+	${SHUTDOWN} -h now "apcupsd remote shutdown"
     ;;
     restartme)
-        echo -n "Restarting APCUPSD Power Management: "
-        THEPID=`cat ${APCPID}`
-        kill ${THEPID}
-        rm -f ${APCPID}
-        rm -f @PWRFAILDIR@/powerfail
-        rm -f @nologdir@/nologin
-        sleep 5
-        `${APCUPSD}`
-        echo "apcupsd"
+	echo -n "Restarting APCUPSD Power Management: "
+	THEPID=`cat ${APCPID}`
+	kill ${THEPID}
+	rm -f ${APCPID}
+	rm -f @PWRFAILDIR@/powerfail
+	rm -f @nologdir@/nologin
+	sleep 5
+	`${APCUPSD}`
+	echo "apcupsd"
     ;;
     startselftest)
     ;;
     endselftest)
     ;;
     mastertimeout)
-        echo "Warning connection to master lost." | wall
+	echo "Warning connection to master lost." | wall
     ;;
     masterconnect)
-        echo "Connection to master established." | wall
+	echo "Connection to master established." | wall
     ;;
-    *)  echo "Usage: ${0##*/} command"
-        echo "       warning: this script is intended to be launched by"
-        echo "       apcupsd and should never be launched by users."
-        exit 1
+    *)	echo "Usage: ${0##*/} command"
+	echo "	     warning: this script is intended to be launched by"
+	echo "	     apcupsd and should never be launched by users."
+	exit 1
     ;;
 esac
diff --git a/platforms/sun/apccontrol.in b/platforms/sun/apccontrol.in
--- a/platforms/sun/apccontrol.in
+++ b/platforms/sun/apccontrol.in
@@ -39,91 +39,92 @@ POWERFAILDIR=@PWRFAILDIR@
 #
 if [ -f ${SCRIPTDIR}/${1} -a -x ${SCRIPTDIR}/${1} ]
 then
-        ${SCRIPTDIR}/${1} ${2} ${3} ${4}
-        # exit code 99 means he does not want us to do default action
-        if [ $? = 99 ] ; then
-                exit 0
-        fi
+	${SCRIPTDIR}/${1} ${2} ${3} ${4}
+	# exit code 99 means he does not want us to do default action
+	if [ $? = 99 ] ; then
+		exit 0
+	fi
 fi
 
 case "$1" in
-        killpower)
-                ${APCUPSD} --killpower
-        ;;
-        commfailure)
-                printf "Warning serial port communications with UPS lost." | wall -a
-        ;;
-        commok)
-                printf "Serial communciations with UPS restored." | wall -a
-        ;;
-        powerout)
-                printf "Warning power loss detected." | wall -a
-        ;;
-        onbattery)
-                printf "Power failure. Running on UPS batteries." | wall -a
-        ;;
-        failing)
-                printf "UPS battery power exhaused. Doing shutdown.\n" | wall -a
-        ;;
-        timeout)
-                printf "UPS battery runtime limit exceded. Doing shutdown.\n" | wall -a
-        ;;
-        loadlimit)
-                printf "UPS battery discharge limit reached. Doing shutdown.\n" | wall -a
-        ;;
-        runlimit)
-                printf "UPS battery runtime percent reached. Doing shutdown.\n" \
-                        | wall -a
-        ;;
-        doreboot)
-                printf "Beginning Reboot Sequence" | wall -a
-                ${SHUTDOWN} -y -g0 -i6 "apcupsd initiated reboot"
-        ;;
-        doshutdown)
-                printf "Beginning Shutdown Sequence" | wall -a
-                ${SHUTDOWN} -y -g0 -i0 "apcupsd initiated shutdown"
-        ;;
-        mainsback)
-                printf "Power has returned..." | wall -a
-        ;;
-        annoyme)
-                printf "Power problems please logoff." | wall -a
-        ;;
-        emergency)
-                printf "Emergency Shutdown. Possible UPS battery failure." \
-                        | wall -a
-                ${SHUTDOWN} -y -g0 -i0 "apcupsd emergency shutdown"
-        ;;
-        changeme)
-                printf "Emergency! UPS batteries have failed\nChange them NOW" \
-                        | wall -a
-        ;;
-        remotedown)
-                printf "Remote Shutdown.\nBeginning Shutdown Sequence." | wall -a
-                ${SHUTDOWN} -y -g0 -i0 "apcupsd remote shutdown"
-        ;;
-        restartme)
-                echo -n "Restarting APCUPSD Power Management: "
-                THEPID=`cat ${APCPID}`
-                kill ${THEPID}
-                rm -f ${APCPID}
-                rm -f ${PWRFAILDIR}/powerfail
-                `${APCUPSD}`
-                echo "apcupsd"
-        ;;
-        startselftest)
-        ;;
-        endselftest)
-        ;;
-        mastertimeout)
-              printf "Warning connection to master lost." | wall -a
-        ;;
-        masterconnect)
-              printf "Connection to master established." | wall -a
-        ;;
-        *)      echo "Usage: ${0##*/} command"
-                echo "       warning: this script is intended to be launched by"
-                echo "       apcupsd and should never be launched by users."
-                exit 1
-        ;;
+	killpower)
+		sleep 10
+		${APCUPSD} --killpower
+	;;
+	commfailure)
+		printf "Warning serial port communications with UPS lost." | wall -a
+	;;
+	commok)
+		printf "Serial communciations with UPS restored." | wall -a
+	;;
+	powerout)
+		printf "Warning power loss detected." | wall -a
+	;;
+	onbattery)
+		printf "Power failure. Running on UPS batteries." | wall -a
+	;;
+	failing)
+		printf "UPS battery power exhaused. Doing shutdown.\n" | wall -a
+	;;
+	timeout)
+		printf "UPS battery runtime limit exceded. Doing shutdown.\n" | wall -a
+	;;
+	loadlimit)
+		printf "UPS battery discharge limit reached. Doing shutdown.\n" | wall -a
+	;;
+	runlimit)
+		printf "UPS battery runtime percent reached. Doing shutdown.\n" \
+			| wall -a
+	;;
+	doreboot)
+		printf "Beginning Reboot Sequence" | wall -a
+		${SHUTDOWN} -y -g0 -i6 "apcupsd initiated reboot"
+	;;
+	doshutdown)
+		printf "Beginning Shutdown Sequence" | wall -a
+		${SHUTDOWN} -y -g0 -i0 "apcupsd initiated shutdown"
+	;;
+	mainsback)
+		printf "Power has returned..." | wall -a
+	;;
+	annoyme)
+		printf "Power problems please logoff." | wall -a
+	;;
+	emergency)
+		printf "Emergency Shutdown. Possible UPS battery failure." \
+			| wall -a
+		${SHUTDOWN} -y -g0 -i0 "apcupsd emergency shutdown"
+	;;
+	changeme)
+		printf "Emergency! UPS batteries have failed\nChange them NOW" \
+			| wall -a
+	;;
+	remotedown)
+		printf "Remote Shutdown.\nBeginning Shutdown Sequence." | wall -a
+		${SHUTDOWN} -y -g0 -i0 "apcupsd remote shutdown"
+	;;
+	restartme)
+		echo -n "Restarting APCUPSD Power Management: "
+		THEPID=`cat ${APCPID}`
+		kill ${THEPID}
+		rm -f ${APCPID}
+		rm -f ${PWRFAILDIR}/powerfail
+		`${APCUPSD}`
+		echo "apcupsd"
+	;;
+	startselftest)
+	;;
+	endselftest)
+	;;
+	mastertimeout)
+	      printf "Warning connection to master lost." | wall -a
+	;;
+	masterconnect)
+	      printf "Connection to master established." | wall -a
+	;;
+	*)	echo "Usage: ${0##*/} command"
+		echo "	     warning: this script is intended to be launched by"
+		echo "	     apcupsd and should never be launched by users."
+		exit 1
+	;;
 esac
