Add some default msgs to ./configure

diff --git a/autoconf/configure.in b/autoconf/configure.in
--- a/autoconf/configure.in
+++ b/autoconf/configure.in
@@ -173,8 +173,8 @@ fi
 AC_MSG_CHECKING(for pthreads)
 
 AC_ARG_ENABLE(pthreads, [
-  --enable-pthreads        Enable pthreads
-  --disable-pthreads       No pthreads (default)],
+  --enable-pthreads	   Enable pthreads
+  --disable-pthreads	   No pthreads (default)],
 with_pthreads=$enableval)
 
 if test "$with_pthreads" != no; then
@@ -229,7 +229,7 @@ else
     AC_PATH_PROGS(APCUPSD_MAIL, mail, no)
     if test "$APCUPSD_MAIL" = "no"
     then
-        echo 'WARNING: mail program not found !'
+	echo 'WARNING: mail program not found !'
     fi
 fi
 
@@ -639,7 +639,7 @@ LIBGDOBJ=
 CGI_IMGFMT=
 SYS_GD_FOUND=no
 AC_ARG_ENABLE(cgi,
-  [  --enable-cgi             Compile CGI programs],
+  [  --enable-cgi	      Compile CGI programs],
   [
    if test "$enableval" = "yes"
    then
@@ -650,22 +650,22 @@ dnl
 dnl First search for system library that defines gdImagePng
      AC_CHECK_LIB(gd, gdImagePng,
        [
-         echo '  using PNG file format (/usr/lib).'
-         AC_DEFINE(SYS_IMGFMT_PNG)
-         LIBS="$LIBS -lgd"
-         SYS_GD_FOUND=yes
+	 echo '  using PNG file format (/usr/lib).'
+	 AC_DEFINE(SYS_IMGFMT_PNG)
+	 LIBS="$LIBS -lgd"
+	 SYS_GD_FOUND=yes
        ], [], [])
 dnl
 dnl Second search for system library that defines gdImageGif
      if test "${SYS_GD_FOUND}" = "no"
      then
        AC_CHECK_LIB(gd, gdImageGif,
-         [
-           echo '  using GIF file format (/usr/lib).'
-           AC_DEFINE(SYS_IMGFMT_GIF)
-           LIBS="$LIBS -lgd"
-           SYS_GD_FOUND=yes
-         ], [], [])
+	 [
+	   echo '  using GIF file format (/usr/lib).'
+	   AC_DEFINE(SYS_IMGFMT_GIF)
+	   LIBS="$LIBS -lgd"
+	   SYS_GD_FOUND=yes
+	 ], [], [])
      fi
 dnl
 dnl Third in /usr/local search for system library that defines gdImagePng
@@ -678,12 +678,12 @@ dnl Third in /usr/local search for system library that defines gdImagePng
 dnl Destroy cached value
        unset ac_cv_lib_gd_gdImagePng
        AC_CHECK_LIB(gd, gdImagePng,
-         [
-           echo '  using PNG file format (/usr/local/lib).'
-           AC_DEFINE(SYS_IMGFMT_PNG)
-           LIBS="$LIBS -lgd"
-           SYS_GD_FOUND=yes
-         ], [], [])
+	 [
+	   echo '  using PNG file format (/usr/local/lib).'
+	   AC_DEFINE(SYS_IMGFMT_PNG)
+	   LIBS="$LIBS -lgd"
+	   SYS_GD_FOUND=yes
+	 ], [], [])
      fi
 dnl
 dnl Fourth in /usr/local search for system library that defines gdImageGif
@@ -692,12 +692,12 @@ dnl Fourth in /usr/local search for system library that defines gdImageGif
 dnl Destroy cached value
        unset ac_cv_lib_gd_gdImageGif
        AC_CHECK_LIB(gd, gdImageGif,
-         [
-           echo '  using GIF file format (/usr/local/lib).'
-           AC_DEFINE(SYS_IMGFMT_GIF)
-           LIBS="$LIBS -lgd"
-           SYS_GD_FOUND=yes
-         ], [], [])
+	 [
+	   echo '  using GIF file format (/usr/local/lib).'
+	   AC_DEFINE(SYS_IMGFMT_GIF)
+	   LIBS="$LIBS -lgd"
+	   SYS_GD_FOUND=yes
+	 ], [], [])
      fi
 dnl
 dnl As last resort, use provided GD library v1.2
@@ -705,24 +705,24 @@ dnl As last resort, use provided GD library v1.2
      then
        if test -d src/gd1.2
        then
-         CPPFLAGS=${_cppflags}
-         LDFLAGS=${_ldflags}
-         GDINCLUDE='-I$(topdir)/src/gd1.2'
-         LIBGD=gd1.2
-         LIBGDOBJ='$(topdir)/src/gd1.2/libgd.a'
-         AC_DEFINE(IMGFMT_GIF)
+	 CPPFLAGS=${_cppflags}
+	 LDFLAGS=${_ldflags}
+	 GDINCLUDE='-I$(topdir)/src/gd1.2'
+	 LIBGD=gd1.2
+	 LIBGDOBJ='$(topdir)/src/gd1.2/libgd.a'
+	 AC_DEFINE(IMGFMT_GIF)
        else
-         echo 'Your system lacks the GD library for compiling CGI'
-         echo 'programs. Please download this library from'
-         echo
-         echo 'ftp://ftp.apcupsd.com/pub/apcupsd/contrib/gd1.2.tar.gz'
-         echo
-         echo 'Untar the file inside the src/ directory so that'
-         echo 'the library is in src/gd1.2/ then you can succesfully'
-         echo 're-run the ./configure script.'
-         echo
-         echo 'Alternatively you can disable the CGI support.'
-         exit 1
+	 echo 'Your system lacks the GD library for compiling CGI'
+	 echo 'programs. Please download this library from'
+	 echo
+	 echo 'ftp://ftp.apcupsd.com/pub/apcupsd/contrib/gd1.2.tar.gz'
+	 echo
+	 echo 'Untar the file inside the src/ directory so that'
+	 echo 'the library is in src/gd1.2/ then you can succesfully'
+	 echo 're-run the ./configure script.'
+	 echo
+	 echo 'Alternatively you can disable the CGI support.'
+	 exit 1
        fi
      fi
 	 if test x"$GDINCLUDE" = x
@@ -730,14 +730,14 @@ dnl As last resort, use provided GD library v1.2
 	   AC_CHECK_HEADER(gd.h, [ GDHEAD= ],
 	     [
 	       AC_CHECK_HEADER(gd/gd.h, [ GDHEAD="gd/" ],
-           [
-             echo 'Found system GD library but no header file.'
-             echo 'Please find the file gd.h in your system'
-             echo 'include directories and report its position'
-             echo 'to apcupsd-devel@apcupsd.com'
-             exit 1
-           ])
-         ])
+	   [
+	     echo 'Found system GD library but no header file.'
+	     echo 'Please find the file gd.h in your system'
+	     echo 'include directories and report its position'
+	     echo 'to apcupsd-devel@apcupsd.com'
+	     exit 1
+	   ])
+	 ])
        AC_SUBST(GDHEAD)
 	 fi
    fi
@@ -764,7 +764,7 @@ dnl Check for enable of drivers
 dnl
 AC_ARG_ENABLE(apcsmart, [
   --enable-apcsmart	       Compile APC Smart UPS driver (default)
-  --disable-apcsmart       No APC Smart UPS driver],
+  --disable-apcsmart	   No APC Smart UPS driver],
 	[ if test "$enableval" = "yes" ; then
 dnl
 dnl This is for C code inclusion
@@ -795,8 +795,8 @@ AC_ARG_ENABLE(dumb, [
 	])
 
 AC_ARG_ENABLE(usb, [
-  --enable-usb             Compile USB UPS code
-  --disable-usb            No USB UPS code (default)],
+  --enable-usb		   Compile USB UPS code
+  --disable-usb 	   No USB UPS code (default)],
 	[ if test "$enableval" = "yes" ; then
 	if test "$host_os" = "linux-gnu"
 	then
@@ -810,13 +810,13 @@ AC_ARG_ENABLE(usb, [
     [])
 
 AC_ARG_ENABLE(net, [
-  --enable-net             Compile NETWORKING UPS code
-  --disable-net            No NETWORKING UPS code (default)],
+  --enable-net		   Compile NETWORKING UPS code
+  --disable-net 	   No NETWORKING UPS code (default)],
 	[ if test "$enableval" = "yes" ; then
-        AC_DEFINE(HAVE_NET_DRIVER)
-        AC_DEFINE(HAVE_NISLIB)
-        NET_DRIVER="net"
-        AC_SUBST(NET_DRIVER)
+	AC_DEFINE(HAVE_NET_DRIVER)
+	AC_DEFINE(HAVE_NISLIB)
+	NET_DRIVER="net"
+	AC_SUBST(NET_DRIVER)
 	fi],
     [])
 
@@ -826,8 +826,8 @@ dnl If the crypto library is needed for snmp, autodetect it
 dnl
 SNMP_DRIVER_ENABLED="no"
 AC_ARG_ENABLE(snmp, [
-  --enable-snmp            Compile SNMP UPS code
-  --disable-snmp           No SNMP UPS code (default)],
+  --enable-snmp 	   Compile SNMP UPS code
+  --disable-snmp	   No SNMP UPS code (default)],
 	[ if test "$enableval" = "yes" ; then
 		SNMP_DRIVER_ENABLED="yes"
 		AC_CHECK_LIB(crypto, EVP_DigestInit,
@@ -846,8 +846,8 @@ if test "$SNMP_DRIVER_ENABLED" = "yes"; then
 fi
 
 AC_ARG_ENABLE(test, [
-  --enable-test            Compile TEST driver code
-  --disable-test           No TEST driver (default)],
+  --enable-test 	   Compile TEST driver code
+  --disable-test	   No TEST driver (default)],
    [ if test "$enableval" = "yes" ; then
 	AC_DEFINE(HAVE_TEST_DRIVER)
 	TEST_DRIVER="test"
@@ -859,8 +859,8 @@ dnl Enable NIS code
 NISSRV_ENABLED=no
 APCNISD=
 AC_ARG_ENABLE(nis, [
-  --enable-nis             Compile NIS server (default)
-  --disable-nis            No NIS server],
+  --enable-nis		   Compile NIS server (default)
+  --disable-nis 	   No NIS server],
    [ if test "$enableval" = "yes" ; then
 	AC_DEFINE(HAVE_NISSERVER)
     AC_DEFINE(HAVE_NISLIB)
@@ -878,8 +878,8 @@ AC_SUBST(APCNISD)
 dnl Enable old network code
 OLDNET_ENABLED=no
 AC_ARG_ENABLE(oldnet, [
-  --enable-oldnet          Compile old network server
-  --disable-oldnet         No old network server (default)],
+  --enable-oldnet	   Compile old network server
+  --disable-oldnet	   No old network server (default)],
    [ if test "$enableval" = "yes" ; then
 	   AC_DEFINE(HAVE_OLDNET)
        OLDNET_ENABLED=yes
@@ -891,7 +891,7 @@ dnl Pickup any css_dir specification
 dnl
 CSS_DIR=
 AC_ARG_WITH(css-dir,
-	[  --with-css-dir=DIR      Specify Style Sheet directory (default=)],
+	[  --with-css-dir=DIR	   Specify Style Sheet directory (default=)],
 	[
 	   CSS_DIR="$withval";
 	]
@@ -899,7 +899,7 @@ AC_ARG_WITH(css-dir,
 
 CGIBIN="/etc/apcupsd"
 AC_ARG_WITH(cgi-bin,
-	[  --with-cgi-bin=DIR      Specify cgi-bin directory (default=/etc/apcupsd/cgi)],
+	[  --with-cgi-bin=DIR	   Specify cgi-bin directory (default=/etc/apcupsd/cgi)],
 	[
 	   CGIBIN="$withval";
 	]
@@ -912,7 +912,7 @@ dnl	use option --enable-powerflute to compile powerflute
 dnl
 POWERFLUTE_ENABLE="no"
 AC_ARG_ENABLE(powerflute,
-	[  --enable-powerflute      Compile powerflute program],
+	[  --enable-powerflute	    Compile powerflute program],
 	[ if test "$enableval" = "yes" ; then
 	POWERFLUTE_ENABLE="yes"
 	    AC_CHECK_LIB(ncurses, initscr,
@@ -1378,12 +1378,12 @@ openserver)
   ;;
 mandrake)
     DISTVER=`cat /etc/mandrake-release | grep release |\
-                cut -f 5 -d ' '`
+		cut -f 5 -d ' '`
     DFILES="\
-        platforms/apccontrol \
-        platforms/mandrake/Makefile \
-        platforms/mandrake/apcupsd \
-        platforms/mandrake/awkhaltprog"
+	platforms/apccontrol \
+	platforms/mandrake/Makefile \
+	platforms/mandrake/apcupsd \
+	platforms/mandrake/awkhaltprog"
   ;;
 redhat)
 	DISTVER=`cat /etc/redhat-release | grep release |\
@@ -1458,9 +1458,9 @@ darwin)
     PIDDIR=/var/run
     LOCKDIR=/var/tmp
     DFILES="\
-        platforms/apccontrol \
-        platforms/darwin/Makefile \
-        platforms/darwin/apcupsd"
+	platforms/apccontrol \
+	platforms/darwin/Makefile \
+	platforms/darwin/apcupsd"
     LDFLAGS="${LDFLAGS} -m"
   ;;
 unknown)
@@ -1481,34 +1481,34 @@ dnl
 dnl Allow user to set nologdir
 dnl
 AC_ARG_WITH(nologin,
-	[  --with-nologin=DIR      Specify nologin file directory (default /etc)],
+	[  --with-nologin=DIR	   Specify nologin file directory (default /etc)],
 	[ nologdir="$withval"; ]
 )
 
 # now allow the user to specify the PID directory
 AC_ARG_WITH(pid-dir,
-	[  --with-pid-dir=DIR      Specify PIDDIR directory],
+	[  --with-pid-dir=DIR	   Specify PIDDIR directory (default is OS dependent)],
 	[
 		PIDDIR="$withval";
 	]
 )
 # now allow user to specify LOGDIR
 AC_ARG_WITH(log-dir,
-	[  --with-log-dir=DIR      Specify EVENTS and STATUS directory],
+	[  --with-log-dir=DIR	   Specify EVENTS and STATUS directory (default is OS dependent)],
 	[
 		LOGDIR="$withval";
 	]
 )
 # now allow user to specify LOCKDIR
 AC_ARG_WITH(lock-dir,
-	[  --with-lock-dir=DIR     Specify serial port lock directory],
+	[  --with-lock-dir=DIR	   Specify serial port lock directory (default is OS dependent)],
 	[
 		LOCKDIR="$withval";
 	]
 )
 # now allow user to specify PWRFAILDIR
 AC_ARG_WITH(pwrfail-dir,
-	[  --with-pwrfail-dir=DIR  Specify power failure file directory],
+	[  --with-pwrfail-dir=DIR  Specify power failure file directory (default is OS dependent)],
 	[
 		PWRFAILDIR="$withval";
 	]
@@ -1525,7 +1525,7 @@ AC_ARG_WITH(serial-dev,
 
 # now allow user to specify NISPORT
 AC_ARG_WITH(nis-port,
-	[  --with-nis-port=PORT    Specify NIS (CGI) port],
+	[  --with-nis-port=PORT    Specify NIS (CGI) port (default 3551 except Debian)],
 	[
 		NISPORT="$withval";
 	]
@@ -1533,7 +1533,7 @@ AC_ARG_WITH(nis-port,
 
 # now allow user to specify NETPORT
 AC_ARG_WITH(net-port,
-	[  --with-net-port=PORT    Specify Master/slave port],
+	[  --with-net-port=PORT    Specify Master/slave port (default 6666 except Debian)],
 	[
 		NETPORT="$withval";
 	]
@@ -1542,7 +1542,7 @@ AC_ARG_WITH(net-port,
 
 # now allow user to specify UPSTYPE
 AC_ARG_WITH(upstype,
-	[  --with-upstype=TYPE     Specify the UPS type],
+	[  --with-upstype=TYPE	   Specify the UPS type],
 	[
 		UPSTYPE="$withval";
 	]
diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -16,52 +16,52 @@ ac_default_prefix=/etc
 ac_default_prefix=/usr
 ac_help="$ac_help
 
-  --enable-pthreads        Enable pthreads
-  --disable-pthreads       No pthreads (default)"
+  --enable-pthreads	   Enable pthreads
+  --disable-pthreads	   No pthreads (default)"
 ac_help="$ac_help
   --with-libwrap[=DIR]      Compile in libwrap (tcp_wrappers) support"
 ac_help="$ac_help
-  --enable-cgi             Compile CGI programs"
+  --enable-cgi	      Compile CGI programs"
 ac_help="$ac_help
   --enable-install-distdir Install distribution"
 ac_help="$ac_help
 
   --enable-apcsmart	       Compile APC Smart UPS driver (default)
-  --disable-apcsmart       No APC Smart UPS driver"
+  --disable-apcsmart	   No APC Smart UPS driver"
 ac_help="$ac_help
 
   --enable-dumb 	       Compile dumb UPS driver (default)
   --disable-dumb	       No dumb UPS driver"
 ac_help="$ac_help
 
-  --enable-usb             Compile USB UPS code
-  --disable-usb            No USB UPS code (default)"
+  --enable-usb		   Compile USB UPS code
+  --disable-usb 	   No USB UPS code (default)"
 ac_help="$ac_help
 
-  --enable-net             Compile NETWORKING UPS code
-  --disable-net            No NETWORKING UPS code (default)"
+  --enable-net		   Compile NETWORKING UPS code
+  --disable-net 	   No NETWORKING UPS code (default)"
 ac_help="$ac_help
 
-  --enable-snmp            Compile SNMP UPS code
-  --disable-snmp           No SNMP UPS code (default)"
+  --enable-snmp 	   Compile SNMP UPS code
+  --disable-snmp	   No SNMP UPS code (default)"
 ac_help="$ac_help
 
-  --enable-test            Compile TEST driver code
-  --disable-test           No TEST driver (default)"
+  --enable-test 	   Compile TEST driver code
+  --disable-test	   No TEST driver (default)"
 ac_help="$ac_help
 
-  --enable-nis             Compile NIS server (default)
-  --disable-nis            No NIS server"
+  --enable-nis		   Compile NIS server (default)
+  --disable-nis 	   No NIS server"
 ac_help="$ac_help
 
-  --enable-oldnet          Compile old network server
-  --disable-oldnet         No old network server (default)"
+  --enable-oldnet	   Compile old network server
+  --disable-oldnet	   No old network server (default)"
 ac_help="$ac_help
-  --with-css-dir=DIR      Specify Style Sheet directory (default=)"
+  --with-css-dir=DIR	   Specify Style Sheet directory (default=)"
 ac_help="$ac_help
-  --with-cgi-bin=DIR      Specify cgi-bin directory (default=/etc/apcupsd/cgi)"
+  --with-cgi-bin=DIR	   Specify cgi-bin directory (default=/etc/apcupsd/cgi)"
 ac_help="$ac_help
-  --enable-powerflute      Compile powerflute program"
+  --enable-powerflute	    Compile powerflute program"
 ac_help="$ac_help
   --enable-nls             enable Native Language Support"
 ac_help="$ac_help
@@ -71,23 +71,23 @@ ac_help="$ac_help
 ac_help="$ac_help
   --with-distname=NAME    Specify DISTNAME"
 ac_help="$ac_help
-  --with-nologin=DIR      Specify nologin file directory (default /etc)"
+  --with-nologin=DIR	   Specify nologin file directory (default /etc)"
 ac_help="$ac_help
-  --with-pid-dir=DIR      Specify PIDDIR directory"
+  --with-pid-dir=DIR	   Specify PIDDIR directory (default is OS dependent)"
 ac_help="$ac_help
-  --with-log-dir=DIR      Specify EVENTS and STATUS directory"
+  --with-log-dir=DIR	   Specify EVENTS and STATUS directory (default is OS dependent)"
 ac_help="$ac_help
-  --with-lock-dir=DIR     Specify serial port lock directory"
+  --with-lock-dir=DIR	   Specify serial port lock directory (default is OS dependent)"
 ac_help="$ac_help
-  --with-pwrfail-dir=DIR  Specify power failure file directory"
+  --with-pwrfail-dir=DIR  Specify power failure file directory (default is OS dependent)"
 ac_help="$ac_help
   --with-serial-dev=DEV   Specify serial port device"
 ac_help="$ac_help
-  --with-nis-port=PORT    Specify NIS (CGI) port"
+  --with-nis-port=PORT    Specify NIS (CGI) port (default 3551 except Debian)"
 ac_help="$ac_help
-  --with-net-port=PORT    Specify Master/slave port"
+  --with-net-port=PORT    Specify Master/slave port (default 6666 except Debian)"
 ac_help="$ac_help
-  --with-upstype=TYPE     Specify the UPS type"
+  --with-upstype=TYPE	   Specify the UPS type"
 ac_help="$ac_help
   --with-upscable=CABLE   Specify the UPS cable"
 
@@ -1500,7 +1500,7 @@ test -n "$APCUPSD_MAIL" || APCUPSD_MAIL="no"
 
     if test "$APCUPSD_MAIL" = "no"
     then
-        echo 'WARNING: mail program not found !'
+	echo 'WARNING: mail program not found !'
     fi
 fi
 
@@ -5297,13 +5297,13 @@ fi
 if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
   echo "$ac_t""yes" 1>&6
   
-         echo '  using PNG file format (/usr/lib).'
-         cat >> confdefs.h <<\EOF
+	 echo '  using PNG file format (/usr/lib).'
+	 cat >> confdefs.h <<\EOF
 #define SYS_IMGFMT_PNG 1
 EOF
 
-         LIBS="$LIBS -lgd"
-         SYS_GD_FOUND=yes
+	 LIBS="$LIBS -lgd"
+	 SYS_GD_FOUND=yes
        
 else
   echo "$ac_t""no" 1>&6
@@ -5347,14 +5347,14 @@ fi
 if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
   echo "$ac_t""yes" 1>&6
   
-           echo '  using GIF file format (/usr/lib).'
-           cat >> confdefs.h <<\EOF
+	   echo '  using GIF file format (/usr/lib).'
+	   cat >> confdefs.h <<\EOF
 #define SYS_IMGFMT_GIF 1
 EOF
 
-           LIBS="$LIBS -lgd"
-           SYS_GD_FOUND=yes
-         
+	   LIBS="$LIBS -lgd"
+	   SYS_GD_FOUND=yes
+	 
 else
   echo "$ac_t""no" 1>&6
 fi
@@ -5403,14 +5403,14 @@ fi
 if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
   echo "$ac_t""yes" 1>&6
   
-           echo '  using PNG file format (/usr/local/lib).'
-           cat >> confdefs.h <<\EOF
+	   echo '  using PNG file format (/usr/local/lib).'
+	   cat >> confdefs.h <<\EOF
 #define SYS_IMGFMT_PNG 1
 EOF
 
-           LIBS="$LIBS -lgd"
-           SYS_GD_FOUND=yes
-         
+	   LIBS="$LIBS -lgd"
+	   SYS_GD_FOUND=yes
+	 
 else
   echo "$ac_t""no" 1>&6
 fi
@@ -5455,14 +5455,14 @@ fi
 if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
   echo "$ac_t""yes" 1>&6
   
-           echo '  using GIF file format (/usr/local/lib).'
-           cat >> confdefs.h <<\EOF
+	   echo '  using GIF file format (/usr/local/lib).'
+	   cat >> confdefs.h <<\EOF
 #define SYS_IMGFMT_GIF 1
 EOF
 
-           LIBS="$LIBS -lgd"
-           SYS_GD_FOUND=yes
-         
+	   LIBS="$LIBS -lgd"
+	   SYS_GD_FOUND=yes
+	 
 else
   echo "$ac_t""no" 1>&6
 fi
@@ -5472,27 +5472,27 @@ fi
      then
        if test -d src/gd1.2
        then
-         CPPFLAGS=${_cppflags}
-         LDFLAGS=${_ldflags}
-         GDINCLUDE='-I$(topdir)/src/gd1.2'
-         LIBGD=gd1.2
-         LIBGDOBJ='$(topdir)/src/gd1.2/libgd.a'
-         cat >> confdefs.h <<\EOF
+	 CPPFLAGS=${_cppflags}
+	 LDFLAGS=${_ldflags}
+	 GDINCLUDE='-I$(topdir)/src/gd1.2'
+	 LIBGD=gd1.2
+	 LIBGDOBJ='$(topdir)/src/gd1.2/libgd.a'
+	 cat >> confdefs.h <<\EOF
 #define IMGFMT_GIF 1
 EOF
 
        else
-         echo 'Your system lacks the GD library for compiling CGI'
-         echo 'programs. Please download this library from'
-         echo
-         echo 'ftp://ftp.apcupsd.com/pub/apcupsd/contrib/gd1.2.tar.gz'
-         echo
-         echo 'Untar the file inside the src/ directory so that'
-         echo 'the library is in src/gd1.2/ then you can succesfully'
-         echo 're-run the ./configure script.'
-         echo
-         echo 'Alternatively you can disable the CGI support.'
-         exit 1
+	 echo 'Your system lacks the GD library for compiling CGI'
+	 echo 'programs. Please download this library from'
+	 echo
+	 echo 'ftp://ftp.apcupsd.com/pub/apcupsd/contrib/gd1.2.tar.gz'
+	 echo
+	 echo 'Untar the file inside the src/ directory so that'
+	 echo 'the library is in src/gd1.2/ then you can succesfully'
+	 echo 're-run the ./configure script.'
+	 echo
+	 echo 'Alternatively you can disable the CGI support.'
+	 exit 1
        fi
      fi
 	 if test x"$GDINCLUDE" = x
@@ -5561,15 +5561,15 @@ if eval "test \"`echo '$ac_cv_header_'$ac_safe`\" = yes"; then
 else
   echo "$ac_t""no" 1>&6
 
-             echo 'Found system GD library but no header file.'
-             echo 'Please find the file gd.h in your system'
-             echo 'include directories and report its position'
-             echo 'to apcupsd-devel@apcupsd.com'
-             exit 1
-           
+	     echo 'Found system GD library but no header file.'
+	     echo 'Please find the file gd.h in your system'
+	     echo 'include directories and report its position'
+	     echo 'to apcupsd-devel@apcupsd.com'
+	     exit 1
+	   
 fi
 
-         
+	 
 fi
 
        
@@ -5664,16 +5664,16 @@ fi
 if test "${enable_net+set}" = set; then
   enableval="$enable_net"
    if test "$enableval" = "yes" ; then
-        cat >> confdefs.h <<\EOF
+	cat >> confdefs.h <<\EOF
 #define HAVE_NET_DRIVER 1
 EOF
 
-        cat >> confdefs.h <<\EOF
+	cat >> confdefs.h <<\EOF
 #define HAVE_NISLIB 1
 EOF
 
-        NET_DRIVER="net"
-        
+	NET_DRIVER="net"
+	
 	fi
 fi
 
@@ -8400,12 +8400,12 @@ openserver)
   ;;
 mandrake)
     DISTVER=`cat /etc/mandrake-release | grep release |\
-                cut -f 5 -d ' '`
+		cut -f 5 -d ' '`
     DFILES="\
-        platforms/apccontrol \
-        platforms/mandrake/Makefile \
-        platforms/mandrake/apcupsd \
-        platforms/mandrake/awkhaltprog"
+	platforms/apccontrol \
+	platforms/mandrake/Makefile \
+	platforms/mandrake/apcupsd \
+	platforms/mandrake/awkhaltprog"
   ;;
 redhat)
 	DISTVER=`cat /etc/redhat-release | grep release |\
@@ -8477,9 +8477,9 @@ darwin)
     PIDDIR=/var/run
     LOCKDIR=/var/tmp
     DFILES="\
-        platforms/apccontrol \
-        platforms/darwin/Makefile \
-        platforms/darwin/apcupsd"
+	platforms/apccontrol \
+	platforms/darwin/Makefile \
+	platforms/darwin/apcupsd"
     LDFLAGS="${LDFLAGS} -m"
   ;;
 unknown)
