Shared memory rework -- see kes02Jun02

diff --git a/trunk/autoconf/configure.in b/trunk/autoconf/configure.in
--- a/trunk/autoconf/configure.in
+++ b/trunk/autoconf/configure.in
@@ -169,6 +169,7 @@ AC_SUBST(PTHREAD_LFLAGS)
 
 
 AC_CYGWIN			dnl Check for cygwin, WINXX port.
+AC_DEFINE(HAVE_CYGWIN)
 if test "$CYGWIN" = "yes"
 then
     WIN32=win32
@@ -177,7 +178,6 @@ then
     APCACCESS=apcaccess
     SMTP=smtp
     APCTEST=apctest
-    AC_DEFINE(HAVE_CYGWIN)
 else
     WIN32=
     WINLIBS=
@@ -210,8 +210,8 @@ then
     echo 'WARNING: mail program not found !'
     if test "$CYGWIN" = "yes"
     then
-        echo 'Hardcoding MAIL to /bin/mail'
-        MAIL='/bin/mail'
+	echo 'Hardcoding MAIL to /bin/mail'
+	MAIL='/bin/mail'
     fi
 fi
 
@@ -281,17 +281,17 @@ dnl ----------------------------------------
 AC_MSG_CHECKING([for syslog])
 
 AC_TRY_LINK(
-        [#include <syslog.h>],
-        [syslog(0, "%s", "test");], AC_MSG_RESULT([yes]),
-          AC_CHECK_LIB(socket, std_syslog,,
-        [echo 'configure: cannot find needed function.'; exit 1]
-          )
-          AC_TRY_LINK(
-            [#include <syslog.h>],
-            [syslog(0, "%s", "test");], AC_MSG_RESULT([yes]),
-            [echo 'configure: cannot find needed function.'; exit 1]
-          )
-        )
+	[#include <syslog.h>],
+	[syslog(0, "%s", "test");], AC_MSG_RESULT([yes]),
+	  AC_CHECK_LIB(socket, std_syslog,,
+	[echo 'configure: cannot find needed function.'; exit 1]
+	  )
+	  AC_TRY_LINK(
+	    [#include <syslog.h>],
+	    [syslog(0, "%s", "test");], AC_MSG_RESULT([yes]),
+	    [echo 'configure: cannot find needed function.'; exit 1]
+	  )
+	)
 
 AC_FUNC_STRFTIME		dnl check for strftime.
 AC_FUNC_SETPGRP 		dnl check for BSD setpgrp.
@@ -567,7 +567,7 @@ AC_ARG_WITH(libwrap,
     _libs=${LIBS}
 
     if test "$withval" = "yes"; then
-        withval="/usr"
+	withval="/usr"
     fi
 
     CPPFLAGS="${CPPFLAGS} -I${withval}/include"
@@ -578,12 +578,12 @@ AC_ARG_WITH(libwrap,
     AC_CHECK_HEADER(tcpd.h,
       AC_MSG_CHECKING(for TCP wrappers library -lwrap)
       AC_TRY_LINK([
-        #include <tcpd.h>
-        int allow_severity = 0;
-        int deny_severity  = 0;
-        struct request_info *req;
+	#include <tcpd.h>
+	int allow_severity = 0;
+	int deny_severity  = 0;
+	struct request_info *req;
       ],[
-        hosts_access (req)],
+	hosts_access (req)],
 
 	    AC_MSG_RESULT(yes)
 	    AC_DEFINE(HAVE_LIBWRAP)
@@ -591,12 +591,12 @@ AC_ARG_WITH(libwrap,
 
 	    AC_MSG_RESULT(no)
 	    CPPFLAGS=${_cppflags}
-        LDFLAGS=${_ldflags}
-        LIBS=${_libs}),
+	LDFLAGS=${_ldflags}
+	LIBS=${_libs}),
 
-        CPPFLAGS=${_cppflags}
-        LDFLAGS=${_ldflags}
-        LIBS=${_libs})
+	CPPFLAGS=${_cppflags}
+	LDFLAGS=${_ldflags}
+	LIBS=${_libs})
     ;;
   esac
 ])
@@ -615,59 +615,59 @@ AC_ARG_ENABLE(cgi,
 	[  --enable-cgi 	       Compile CGI programs],
 	[ if test "$enableval" = "yes" ; then
 	    ENABLE_CGI="yes"
-        CGI=cgi
+	CGI=cgi
 dnl
 dnl First search for system library that defines gdImagePng
 		AC_CHECK_LIB(gd, gdImagePng,
 		  [echo '  using PNG file format.'
-              AC_DEFINE(SYS_IMGFMT_PNG)
-              LIBS="$LIBS -lgd"],
+	      AC_DEFINE(SYS_IMGFMT_PNG)
+	      LIBS="$LIBS -lgd"],
 		  [
 dnl
 dnl Then search for system library that defines gdImageGif
 		  AC_CHECK_LIB(gd, gdImageGif,
 		    [echo '  using GIF file format.'
-              AC_DEFINE(SYS_IMGFMT_GIF)
-              LIBS="$LIBS -lgd"],
-            [
+	      AC_DEFINE(SYS_IMGFMT_GIF)
+	      LIBS="$LIBS -lgd"],
+	    [
 dnl
 dnl As last resort, use provided GD library v1.2
-              if test -d src/gd1.2
-              then
-                GDINCLUDE='-I$(topdir)/src/gd1.2'
-                LIBGD=gd1.2
-                LIBGDOBJ='$(topdir)/src/gd1.2/libgd.a'
-                AC_DEFINE(IMGFMT_GIF)
-              else
-                echo 'Your system lacks the GD library for compiling CGI'
-                echo 'programs. Please download this library from'
-                echo
-                echo 'ftp://ftp.apcupsd.com/pub/apcupsd/contrib/gd1.2.tar.gz'
-                echo
-                echo 'Untar the file inside the src/ directory so that'
-                echo 'the library is in src/gd1.2/ then you can succesfully'
-                echo 're-run the ./configure script.'
-                echo
-                echo 'Alternatively you can disable the CGI support.'
-                exit 1
-              fi
-            ], [])
-          ], [])
-        if test x"$GDINCLUDE" = x
-        then
-          AC_CHECK_HEADER(gd.h, [ GDHEAD= ],
-            [
-              AC_CHECK_HEADER(gd/gd.h, [ GDHEAD="gd/" ],
-                [
-                  echo 'Found system GD library but no header file.'
-                  echo 'Please find the file gd.h in your system'
-                  echo 'include directories and report its position'
-                  echo 'to apcupsd-devel@apcupsd.com'
-                  exit 1
-                ])
-            ])
-          AC_SUBST(GDHEAD)
-        fi
+	      if test -d src/gd1.2
+	      then
+		GDINCLUDE='-I$(topdir)/src/gd1.2'
+		LIBGD=gd1.2
+		LIBGDOBJ='$(topdir)/src/gd1.2/libgd.a'
+		AC_DEFINE(IMGFMT_GIF)
+	      else
+		echo 'Your system lacks the GD library for compiling CGI'
+		echo 'programs. Please download this library from'
+		echo
+		echo 'ftp://ftp.apcupsd.com/pub/apcupsd/contrib/gd1.2.tar.gz'
+		echo
+		echo 'Untar the file inside the src/ directory so that'
+		echo 'the library is in src/gd1.2/ then you can succesfully'
+		echo 're-run the ./configure script.'
+		echo
+		echo 'Alternatively you can disable the CGI support.'
+		exit 1
+	      fi
+	    ], [])
+	  ], [])
+	if test x"$GDINCLUDE" = x
+	then
+	  AC_CHECK_HEADER(gd.h, [ GDHEAD= ],
+	    [
+	      AC_CHECK_HEADER(gd/gd.h, [ GDHEAD="gd/" ],
+		[
+		  echo 'Found system GD library but no header file.'
+		  echo 'Please find the file gd.h in your system'
+		  echo 'include directories and report its position'
+		  echo 'to apcupsd-devel@apcupsd.com'
+		  exit 1
+		])
+	    ])
+	  AC_SUBST(GDHEAD)
+	fi
 	fi])
 
 dnl	
@@ -755,8 +755,8 @@ AC_ARG_ENABLE(snmp, [
 		  [echo '  including crypto library for snmp.'; LIBS="$LIBS -lcrypto"],
 		  [], [])
 	    AC_CHECK_LIB(snmp, snmp_open,
-          [LIBS="$LIBS -lsnmp"],
-          [echo '  disabling SNMP driver.'; SNMP_DRIVER_ENABLED="no"])
+	  [LIBS="$LIBS -lsnmp"],
+	  [echo '  disabling SNMP driver.'; SNMP_DRIVER_ENABLED="no"])
 	fi],
     [])
 
@@ -804,19 +804,19 @@ POWERFLUTE_ENABLE="no"
 AC_ARG_ENABLE(powerflute,
 	[  --enable-powerflute	  Compile powerflute program],
 	[ if test "$enableval" = "yes" ; then
-        POWERFLUTE_ENABLE="yes"
+	POWERFLUTE_ENABLE="yes"
 	    AC_CHECK_LIB(ncurses, initscr,
-        [PL="-lncurses"],
-        [echo '  disabling powerflute.'; POWERFLUTE_ENABLE="no"])
+	[PL="-lncurses"],
+	[echo '  disabling powerflute.'; POWERFLUTE_ENABLE="no"])
 	    AC_CHECK_LIB(menu, new_menu,
-        [PL="$PL -lmenu"],
-        [echo '  disabling powerflute.'; POWERFLUTE_ENABLE="no"])
+	[PL="$PL -lmenu"],
+	[echo '  disabling powerflute.'; POWERFLUTE_ENABLE="no"])
 	    AC_CHECK_LIB(form, new_form,
-        [PL="$PL -lform"],
-        [echo '  disabling powerflute.'; POWERFLUTE_ENABLE="no"])
+	[PL="$PL -lform"],
+	[echo '  disabling powerflute.'; POWERFLUTE_ENABLE="no"])
 	    AC_CHECK_LIB(panel, new_panel,
-        [PL="$PL -lpanel"],
-        [echo '  disabling powerflute.'; POWERFLUTE_ENABLE="no"])
+	[PL="$PL -lpanel"],
+	[echo '  disabling powerflute.'; POWERFLUTE_ENABLE="no"])
 	  fi])
 
 if test "$POWERFLUTE_ENABLE" = "yes"; then
@@ -1253,12 +1253,12 @@ openserver)
   ;;
 mandrake)
     DISTVER=`cat /etc/mandrake-release | grep release |\
-                cut -f 5 -d ' '`
+		cut -f 5 -d ' '`
     DFILES="\
-        distributions/apccontrol \
-        distributions/mandrake/Makefile \
-        distributions/mandrake/apcupsd \
-        distributions/mandrake/awkhaltprog"
+	distributions/apccontrol \
+	distributions/mandrake/Makefile \
+	distributions/mandrake/apcupsd \
+	distributions/mandrake/awkhaltprog"
   ;;
 redhat)
 	DISTVER=`cat /etc/redhat-release | grep release |\
@@ -1333,9 +1333,9 @@ darwin)
     PIDDIR=/var/run
     LOCKDIR=/var/tmp
     DFILES="\
-        platforms/apccontrol \
-        platforms/darwin/Makefile \
-        platforms/darwin/apcupsd"
+	platforms/apccontrol \
+	platforms/darwin/Makefile \
+	platforms/darwin/apcupsd"
     LDFLAGS="${LDFLAGS} -m"
   ;;
 unknown)
@@ -1478,15 +1478,15 @@ dnl
 dnl First entry must always be "variables.mak"
 dnl
 GENERATE_FILES="\
-        autoconf/variables.mak \
+	autoconf/variables.mak \
 		Makefile \
 		autoconf/Makefile \
-        include/Makefile \
-        src/Makefile \
+	include/Makefile \
+	src/Makefile \
 		src/lib/Makefile \
-    	src/drivers/Makefile \
+	src/drivers/Makefile \
 		platforms/Makefile \
-        doc/Makefile \
+	doc/Makefile \
 		platforms/etc/changeme \
 		platforms/etc/commfailure \
 		platforms/etc/commok \
@@ -1580,7 +1580,7 @@ eval mandir=${mandir}
 
 echo "
 
-Configuration:
+Configuration on `date`:
 
   Apcupsd version:	      ${VERSION} (${DATE})
   Source code location:       ${srcdir}
@@ -1614,7 +1614,9 @@ Configuration:
   enable-powerflute:	      ${USE_POWERFLUTE}
   enable-pthreads:	      ${with_pthreads}
   enable-dist-install:	      ${with_distdir}
-  "
+  " > config.out
+
+cat config.out
 
 dnl
 dnl Touch include/config.h since the last file updated was Makefile.
